# Generated by Django 5.0 on 2023-12-24 14:03

import ckeditor_uploader.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('fingerprint', models.CharField(max_length=250, verbose_name='Fingerprint')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=250, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='manufacturer', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Parent Category',
                'verbose_name_plural': 'Parent Categories',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('query', models.CharField(blank=True, max_length=250, verbose_name='Query')),
                ('fingerprint', models.CharField(blank=True, max_length=250, verbose_name='Fingerprint')),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('phone', models.CharField(max_length=250, verbose_name='Phone')),
                ('status', models.CharField(choices=[('in_moderation', 'На модерации'), ('sold', 'Продано'), ('cancelled', 'Отменено')], default='in_moderation', max_length=250, verbose_name='Status')),
                ('in_stock_subtracted', models.BooleanField(default=False, verbose_name='In stock')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.cart', verbose_name='Cart')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.parentcategory', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('product_code', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Product Code')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('features', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Features')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Sale Price')),
                ('in_stock_count', models.PositiveIntegerField(default=9999, verbose_name='In stock count')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views count')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Is recommended')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Is sale')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='LastSeenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('fingerprint', models.CharField(max_length=250, verbose_name='Fingerprint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_seen', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'LastSeenProduct',
                'verbose_name_plural': 'LastSeenProducts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('sub_title', models.CharField(max_length=250, verbose_name='Sub Title')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/gallery', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product Galleries',
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('fingerprint', models.CharField(max_length=250, verbose_name='Fingerprint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'ProductView',
                'verbose_name_plural': 'ProductViews',
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('fingerprint', models.CharField(max_length=250, verbose_name='Fingerprint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'SaveProduct',
                'verbose_name_plural': 'SaveProducts',
                'unique_together': {('product', 'fingerprint')},
            },
        ),
    ]
